name: android-build-and-test

on:
  push:
    branches:
    - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'

      - name: Set up Android SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'sdk'
          java-version: '1.8'
          server-id: github
          server-username: ${{ secrets.GITHUB_USERNAME }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
